version: 0.2

env:
  shell: bash
  variables:
    TERRAFORM_VERSION: 0.12.29

batch:
  fast-fail: false | true
  build-graph:

phases:
  install:
    commands:
      - echo '[INFO] Begin Terraform apply'

  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform apply --auto-approve