version: 0.2

env:
  shell: bash
  variables:
    TERRAFORM_VERSION: 0.12.29

batch:
  fast-fail: false | true

phases:
  install:
    commands:
      - echo '[INFO] Begin Terraform init and validate'
  pre_build:
    commands:
      - terraform init
      - terraform validate
  build:
    commands:
      - terraform plan