version: 0.2

env:
  shell: bash
  variables:
    TERRAFORM_VERSION: 0.12.29

batch:
  fast-fail: false | true

phases:
  install:
    commands:
      - | 
        curl -LO https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
            unzip ./terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/bin && \
            chmod +x /usr/bin/terraform && \
            terraform --version
  pre_build:
    commands:
      - terraform init
      - terraform validate
  build:
    commands:
      - terraform plan